Notes:

I have used the same code for the previous one, but for the exception handling it's done at one place in the main function instead of being dispersed among the whole code.